### ISSUE TITLE
有个疑问想问一下

### ISSUE THREAD

**Issue by Popxie** [Faithree/dy#1]
### 整体的思路就三个步骤：

- 根据分享的视频地址，通过重定向获取整个html信息
- 通过第一步返回来的html信息，截取itemId， dytk 发起二次请求获取uriId
- 最后通过uri参数来调用视频下载接口

我的疑问就是 你咋知道第一个接口返回来的是一个完整的html啊？= =

**Comment by Faithree** [comment]
@Popxie 掘金上有截图，302重定向
![image](https://user-images.githubusercontent.com/21101396/84593348-5c8bce80-ae7e-11ea-86f5-d87f2b66057b.png)
然后访问这个重定向地址，返回的是一个html
![image](https://user-images.githubusercontent.com/21101396/84593373-8644f580-ae7e-11ea-8043-3ec585770e48.png)

**Comment by Popxie** [comment]
哦哦哦 知道了 我没注意到这个 接口 = =  谢谢大佬！
